apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
